
const AllMarkersByCountry = {
  us: {
    markers: [
      {
        id: '1',
        headline: 'U.S. announces new travel restrictions amid novel coronavirus pandemic',
        color: '#FCFEC1',
        city: 'Toronto',
        coordinates: [43.6532, 79.3832],
        value: 100,
        tags: '',
        code: 'CA',
        date: '14 Mar 2020',
        outlet: 'Global News',
        paragraph: 'Donald Trump and Mike Pence announced Saturday that the United States will broaden its European travel ban, adding the United Kingdom and Ireland to its list, and was considering imposing restrictions on travel within the U.S.',
    },
    {
        id: '2',
        headline: 'Trump to provide update on U.S. coronavirus measures, including executive actions',
        color: '#FCFEC1',
        city: 'Toronto',
        coordinates: [43.6532, 79.3832],
        value: 100,
        tags: '',
        code: 'CA',
        date: '11 Mar 2020',
        outlet: 'Global News',
        paragraph: 'U.S. President Donald Trump was considering a national disaster declaration and new travel advisories while Congress unveiled a coronavirus aid package as Washington raced Wednesday to confront the outbreak.',
    },
    {
        id: '3',
        headline: 'Coronavirus: California declares emergency after death',
        color: '#FCFEC1',
        city: 'Toronto',
        coordinates: [43.6532, 79.3832],
        value: 100,
        tags: '',
        code: 'CA',
        date: '5 Mar 2020',
        outlet: 'BBC',
        paragraph: 'California has declared a state of emergency after announcing its first coronavirus death, bringing the US death toll from the disease to 11.',
    },
    {
        id: '4',
        headline: '6 people have died from novel coronavirus in the US as cases nationwide surge',
        color: '#FCFEC1',
        city: 'Toronto',
        coordinates: [43.6532, 79.3832],
        value: 100,
        tags: '',
        code: 'CA',
        date: '3 Mar 2020',
        outlet: 'CNN',
        paragraph: 'Six people have died in Washington state as the United States grapples with more than 100 cases of the disease caused by the novel coronavirus.',
    },
    {
        id: '5',
        headline: 'U.S. House passes sweeping coronavirus aid package, including free testing',
        color: '#FCFEC1',
        city: 'Toronto',
        coordinates: [43.6532, 79.3832],
        value: 100,
        tags: '',
        code: 'CA',
        date: '14 Mar 2020',
        outlet: 'Global News',
        paragraph: 'The U.S. House of Representatives has passed a sweeping coronavirus aid package that includes free testing and paid sick leave for workers.',
    },
    
    
    
    
    
    
    // VPN: BELGIUM
    {
        id: '1',
        headline: 'Despite the state of emergency and an emergency package of corona measures in the US: "Things are going pretty wrong here"',
        color: '#FCFEC1',
        city: 'Brussels',
        coordinates: [50.8503, -4.3517],
        value: 100,
        tags: '',
        code: 'BE',
        date: '14 Mar 2020',
        outlet: 'VRT NWS',
        paragraph: 'The United States is also completely under the spell of the new coronavirus.',
    },
    {
        id: '2',
        headline: 'Lockdown for a third of the US population, "a major ordeal for the US," said President Trump',
        color: '#FCFEC1',
        city: 'Brussels',
        coordinates: [50.8503, -4.3517],
        value: 100,
        tags: '',
        code: 'BE',
        date: '23 Mar 2020',
        outlet: 'VRT NWS',
        paragraph: '"This is a great ordeal for the entire country," said Donald Trump in a White House news conference.',
    },
    {
        id: '3',
        headline: 'China: "America is behind the coronavirus"',
        color: '#FCFEC1',
        city: 'Brussels',
        coordinates: [50.8503, -4.3517],
        value: 100,
        tags: '',
        code: 'BE',
        date: '13 Mar 2020',
        outlet: 'Metro Belgium',
        paragraph: 'A spokesman for the Chinese foreign ministry claims on twitter that the coronavirus originated or was made in the US and that the US military brought it to China.',
    },
    {
        id: '4',
        headline: 'The US now has the most recorded coronavirus infections',
        color: '#FCFEC1',
        city: 'Brussels',
        coordinates: [50.8503, -4.3517],
        value: 100,
        tags: '',
        code: 'BE',
        date: '6 Mar 2020',
        outlet: 'NPO Radio 1',
        paragraph: 'The number of people infected with the coronavirus in the United States has risen to more than 83,000; that is the largest number of infections worldwide.',
    },
    {
        id: '5',
        headline: 'The coronavirus now also reaches America: NBA stars may no longer give high fives (but there is an alternative)',
        color: '#FCFEC1',
        city: 'Brussels',
        coordinates: [50.8503, -4.3517],
        value: 100,
        tags: '',
        code: 'BE',
        date: '3 Mar 2020',
        outlet: 'Het Nieuwsblad',
        paragraph: 'No more giving high fives to fans and signing with your own marker.',
    },
    
    
    
    
    
    
    // VPN: DENMARK
    {
        id: '1',
        headline: 'US has restricted travel to and from these countries amid coronavirus pandemic',
        color: '#FCFEC1',
        city: 'Copenhagen',
        coordinates: [55.6761, -12.5683],
        value: 100,
        tags: '',
        code: 'DK',
        date: '11 Mar 2020',
        outlet: 'FOX News',
        paragraph: 'The Trump administration will suspend travel between European countries and the United States for 30 days.',
    },
    {
        id: '2',
        headline: 'Huge corona scandal rising in US: While calming the population, he sold his shares',
        color: '#FCFEC1',
        city: 'Copenhagen',
        coordinates: [55.6761, -12.5683],
        value: 100,
        tags: '',
        code: 'DK',
        date: '22 Mar 2020',
        outlet: 'TV 2',
        paragraph: 'More than two dozen congressmen are accused of insider trading before the corona crisis hit the United States.',
    },
    {
        id: '3',
        headline: 'David Trads: Bizarre coronakaos may end with Trump´s re-election',
        color: '#FCFEC1',
        city: 'Copenhagen',
        coordinates: [55.6761, -12.5683],
        value: 100,
        tags: '',
        code: 'DK',
        date: '26 Mar 2020',
        outlet: 'Altinget.dk',
        paragraph: 'll analyzes and forecasts made about the outcome of the November US election should now be thrown down the board. Now its all about handling corona.',
    },
    {
        id: '4',
        headline: 'Trump´s travel ban puts stocks and oil prices in the bottom',
        color: '#FCFEC1',
        city: 'Copenhagen',
        coordinates: [55.6761, -12.5683],
        value: 100,
        tags: '',
        code: 'DK',
        date: '12 Mar 2020',
        outlet: 'Ekstra Bladet',
        paragraph: 'It could be felt in Asian stock markets that Trump announced a travel ban from Europe to the US',
    },
    {
        id: '5',
        headline: 'David Trads: Trump is disastrous. We need Churchill',
        color: '#FCFEC1',
        city: 'Copenhagen',
        coordinates: [55.6761, -12.5683],
        value: 100,
        tags: '',
        code: 'DK',
        date: '17 Mar 2020',
        outlet: 'Altinget.dk',
        paragraph: 'We can´t just hope that Trump and the United States take the global leadership in the war we are fighting against the damned virus.',
    },
    
    
    
    
    
    
    // VPN: FINLAND
    {
        id: '1',
        headline: 'The United States now has the highest number of coronavirus infections in the world',
        color: '#FCFEC1',
        city: 'Helsinki',
        coordinates: [60.1699, -24.9384],
        value: 100,
        tags: '',
        code: 'FI',
        date: '27 Mar 2020',
        outlet: 'Helsingin Sanomat',
        paragraph: 'How did the country slip into error one point at a time?',
    },
    {
        id: '2',
        headline: 'Trump bans travel from 26 European countries to the USA because of the coronavirus, Finland is among them',
        color: '#FCFEC1',
        city: 'Helsinki',
        coordinates: [60.1699, -24.9384],
        value: 100,
        tags: '',
        code: 'FI',
        date: '12 Mar 2020',
        outlet: 'Helsingin Sanomat',
        paragraph: 'Restrictions will be adjusted according to circumstances, the president said of the White House.',
    },
    {
        id: '3',
        headline: 'The United States is cutting its aid to Afghanistan by a billion - the reason for the country´s political impasse',
        color: '#FCFEC1',
        city: 'Helsinki',
        coordinates: [60.1699, -24.9384],
        value: 100,
        tags: '',
        code: 'FI',
        date: '24 Mar 2020',
        outlet: 'YLE',
        paragraph: 'The coronavirus is slowing the withdrawal agreed with the Taliban.',
    },
    {
        id: '4',
        headline: 'In the US, half of working-age people in the intensive care unit',
        color: '#FCFEC1',
        city: 'Helsinki',
        coordinates: [60.1699, -24.9384],
        value: 100,
        tags: '',
        code: 'FI',
        date: '19 Mar 2020',
        outlet: 'Helsingin Sanomat',
        paragraph: 'Statistics shatter perception of coronary heart disease, which is mostly dangerous for the elderly.',
    },
    {
        id: '5',
        headline: 'The number of coronary infections in the US quadrupled in two days - the rate in California is even more incomprehensible',
        color: '#FCFEC1',
        city: 'Helsinki',
        coordinates: [60.1699, -24.9384],
        value: 100,
        tags: '',
        code: 'FI',
        date: '20 Mar 2020',
        outlet: 'Iltalehti',
        paragraph: 'In the United States, the coronavirus is spreading rapidly.',
    },
    
    
    
    
    
    
    // VPN: IRELAND
    {
        id: '1',
        headline: 'Irish citizens on cruise ship with 21 coronavirus cases',
        color: '#FCFEC1',
        city: 'Dublin',
        coordinates: [53.3498, -6.2603],
        value: 100,
        tags: '',
        code: 'IE',
        date: '7 Mar 2020',
        outlet: 'RTÉ',
        paragraph: 'More than 200 people have contracted the virus in the United States, and 12 have died, 11 of them in the state of Washington.',
    },
    {
        id: '2',
        headline: 'US coronavirus death toll rises as Chinese cases fall',
        color: '#FCFEC1',
        city: 'Dublin',
        coordinates: [53.3498, -6.2603],
        value: 100,
        tags: '',
        code: 'IE',
        date: '2 Mar 2020',
        outlet: 'RTÉ',
        paragraph: 'The death toll from the new coronavirus in the United States has climbed to six.',
    },
    {
        id: '3',
        headline: 'US extends travel ban to Ireland, UK over coronavirus',
        color: '#FCFEC1',
        city: 'Dublin',
        coordinates: [53.3498, -6.2603],
        value: 100,
        tags: '',
        code: 'IE',
        date: '14 Mar 2020',
        outlet: 'RTÉ',
        paragraph: 'The ban will come into effect at 4am (Irish time) on Tuesday.',
    },
    {
        id: '4',
        headline: 'Trump declares Covid-19 travel ban from most of Europe, excluding Ireland and UK',
        color: '#FCFEC1',
        city: 'Dublin',
        coordinates: [53.3498, -6.2603],
        value: 100,
        tags: '',
        code: 'IE',
        date: '12 Mar 2020',
        outlet: 'RTÉ',
        paragraph: 'US President Donald Trump has announced the suspension of all travel to the United States from the majority of European nations for 30 days.',
    },
    {
        id: '5',
        headline: 'Tom Hanks Got Sick in Australia, Where Coronavirus Testing Isn’t Such a Hassle',
        color: '#FCFEC1',
        city: 'Dublin',
        coordinates: [53.3498, -6.2603],
        value: 100,
        tags: '',
        code: 'IE',
        date: '12 Mar 2020',
        outlet: 'The New York Times',
        paragraph: 'In the United States, little if anything about the testing has been efficient or convenient.',
    },
    
    
    
    
    
    
    // VPN: NORWAY
    {
        id: '1',
        headline: 'The US stops entering Europe for 30 days',
        color: '#FCFEC1',
        city: 'Oslo',
        coordinates: [59.9139, -10.7522],
        value: 100,
        tags: '',
        code: 'NO',
        date: '11 Mar 2020',
        outlet: 'Aftenposten',
        paragraph: 'Trump did not fully acknowledge that the corona virus is spreading in the United States.',
    },
    {
        id: '2',
        headline: 'Trump as a corona expert: - Maybe I have natural abilities',
        color: '#FCFEC1',
        city: 'Oslo',
        coordinates: [59.9139, -10.7522],
        value: 100,
        tags: '',
        code: 'NO',
        date: '7 Mar 2020',
        outlet: 'NRK',
        paragraph: 'The United States has around 330 million inhabitants and has tested around 1,500 people for the new coronavirus.',
    },
    {
        id: '3',
        headline: 'USA : Four in the same family died of coronavirus',
        color: '#FCFEC1',
        city: 'Oslo',
        coordinates: [59.9139, -10.7522],
        value: 100,
        tags: '',
        code: 'NO',
        date: '20 Mar 2020',
        outlet: 'ABC Nyheter',
        paragraph: 'They are among the first victims of the viral epidemic, which is in its early stages in the United States.',
    },
    {
        id: '4',
        headline: 'China threatens to "drown US in corona virus´s powerful sea"',
        color: '#FCFEC1',
        city: 'Oslo',
        coordinates: [59.9139, -10.7522],
        value: 100,
        tags: '',
        code: 'NO',
        date: '18 Mar 2020',
        outlet: 'NRK',
        paragraph: 'The US has previously shut out the large Chinese telecommunications company Huawei.',
    },
    {
        id: '5',
        headline: 'The United States has a major handicap in dealing with the coronavirus: itself',
        color: '#FCFEC1',
        city: 'Oslo',
        coordinates: [59.9139, -10.7522],
        value: 100,
        tags: '',
        code: 'NO',
        date: '16 Mar 2020',
        outlet: 'Bergens Tidende',
        paragraph: 'Verda´s most powerful country seems completely uninhabitable for the corona eruption.',
    },
    
    
    
    
    
    // VPN: SPAIN 
    {
        id: '1',
        headline: 'The US redoubles its measures against the coronavirus and Trump plans to restrict domestic flights',
        color: '#FCFEC1',
        city: 'Madrid',
        coordinates: [40.4168, -3.7038],
        value: 100,
        tags: '',
        code: 'ES',
        date: '13 Mar 2020',
        outlet: 'EL PAÍS',
        paragraph: 'From transportation to culture, through sports, the crisis already alters multiple areas of life in various parts of the country.',
    },
    {
        id: '2',
        headline: 'United States becomes epicenter of pandemic without national strategy',
        color: '#FCFEC1',
        city: 'Madrid',
        coordinates: [40.4168, -3.7038],
        value: 100,
        tags: '',
        code: 'ES',
        date: '28 Mar 2020',
        outlet: 'EL PAÍS',
        paragraph: 'Mississippi limits restrictions and calls out against "models of dictatorships like China," as New York tightens rules.',
    },
    {
        id: '3',
        headline: 'Trump rules out quarantine for New York, focus of the coronavirus in the United States',
        color: '#FCFEC1',
        city: 'Madrid',
        coordinates: [40.4168, -3.7038],
        value: 100,
        tags: '',
        code: 'ES',
        date: '29 Mar 2020',
        outlet: 'La Vanguardia',
        paragraph: 'The President of the United States, Donald Trump, assured this Saturday through a tweet that he believes that a quarantine is necessary.',
    },
    {
        id: '4',
        headline: 'United States and Mexico agree to close the border',
        color: '#FCFEC1',
        city: 'Madrid',
        coordinates: [40.4168, -3.7038],
        value: 100,
        tags: '',
        code: 'ES',
        date: '20 Mar 2020',
        outlet: 'AS',
        paragraph: 'The measure will be applied in all cases, except for emergency reasons.',
    },
    {
        id: '5',
        headline: 'Second death in the USA while the coronavirus spreads on both coasts',
        color: '#FCFEC1',
        city: 'Madrid',
        coordinates: [40.4168, -3.7038],
        value: 100,
        tags: '',
        code: 'ES',
        date: '1 Mar 2020',
        outlet: 'La Vanguardia',
        paragraph: 'The coronavirus is spread throughout the United States. After registering the second death, a man of about 70 years, died in the same area of ​​Seattle where the first one occurred.',
    },
    
    
    
    
    
    // VPN: UNITED KINGDOM
    {
        id: '1',
        headline: 'Coronavirus: California declares emergency after death',
        color: '#FCFEC1',
        city: 'London',
        coordinates: [51.5074, -0.1278],
        value: 100,
        tags: '',
        code: 'UK',
        date: '4 Mar 2020',
        outlet: 'BBC News',
        paragraph: 'California has declared a state of emergency after announcing its first coronavirus death, bringing the US death toll from the disease to 11.',
    },
    {
        id: '2',
        headline: 'Coronavirus: US to add UK and Ireland to European travel ban',
        color: '#FCFEC1',
        city: 'London',
        coordinates: [51.5074, -0.1278],
        value: 100,
        tags: '',
        code: 'UK',
        date: '17 Mar 2020',
        outlet: 'Sky News',
        paragraph: 'The ban will begin at midnight on Monday (0400 GMT), although American citizens will still be able to fly back.',
    },
    {
        id: '3',
        headline: 'US lockdown NOW, crisis till August',
        color: '#FCFEC1',
        city: 'London',
        coordinates: [51.5074, -0.1278],
        value: 100,
        tags: '',
        code: 'UK',
        date: '17 Mar 2020',
        outlet: 'Daily Mail',
        paragraph: 'Trump says there are ´15 days to stop the spread´ and old must stay home, gatherings over 10 people end, and schools, offices bars and restaurants close to beat coronavirus.',
    },
    {
        id: '4',
        headline: 'Coronavirus: Trump suspends travel from Europe to US',
        color: '#FCFEC1',
        city: 'London',
        coordinates: [51.5074, -0.1278],
        value: 100,
        tags: '',
        code: 'UK',
        date: '12 Mar 2020',
        outlet: 'BBC News',
        paragraph: 'US President Donald Trump has announced sweeping travel restrictions on 26 European countries in a bid to combat the spread of the coronavirus.',
    },
    {
        id: '5',
        headline: 'Trump suspends travel from most of Europe amid coronavirus outbreak',
        color: '#FCFEC1',
        city: 'London',
        coordinates: [51.5074, -0.1278],
        value: 100,
        tags: '',
        code: 'UK',
        date: '11 Mar 2020',
        outlet: 'The Guardian',
        paragraph: 'UK among countries exempt from ban as president faces doubts over measure’s effectiveness.',
    },
    
    
    
    
    
    // VPN: HONG KONG
    {
        id: '1',
        headline: 'The United States government recognized that some products for killing new coronavirus are available in Hong Kong',
        color: '#FCFEC1',
        city: 'Hong Kong',
        coordinates: [22.3193, -114.1694],
        value: 100,
        tags: '',
        code: 'HK',
        date: '23 Mar 2020',
        outlet: 'Hong Kong Economic Times-TOPick',
        paragraph: 'The United States Environmental Protection Agency (Environmental Protection Agency, hereinafter referred to as EPA) released a list of disinfectants that can kill new coronaviruses, some of which are available in Hong Kong.',
    },
    {
        id: '2',
        headline: 'Expect antimalarial drugs to treat pneumonia in Wuhan',
        color: '#FCFEC1',
        city: 'Hong Kong',
        coordinates: [22.3193, -114.1694],
        value: 100,
        tags: '',
        code: 'HK',
        date: '20 Mar 2020',
        outlet: 'Central Radio',
        paragraph: 'US President Trump said on the 19th that the United States is accelerating the process of using anti-malarial drugs to treat the 2019 coronavirus disease (COVID-19) commonly known as Wuhan pneumonia.',
    },
    {
        id: '3',
        headline: 'Johnson & Johnson Tests New Coronary Pneumonia Vaccine Abbott in September',
        color: '#FCFEC1',
        city: 'Hong Kong',
        coordinates: [22.3193, -114.1694],
        value: 100,
        tags: '',
        code: 'HK',
        date: '31 Mar 2020',
        outlet: 'now News',
        paragraph: 'New coronavirus rapid testing and vaccine development have progressed, stimulating Johnson & Johnson and Abbott stocks listed in the United States to jump more than half of their shares overnight.',
    },
    {
        id: '4',
        headline: 'Bill Gates Zuckerberg teamed up to fight the plague',
        color: '#FCFEC1',
        city: 'Hong Kong',
        coordinates: [22.3193, -114.1694],
        value: 100,
        tags: '',
        code: 'HK',
        date: '28 Mar 2020',
        outlet: 'Hong Kong Economic Times',
        paragraph: 'Gates and Zuckerberg, the U.S. Science and Technology giant, joined forces to fight the virus.',
    },
    {
        id: '5',
        headline: 'Mask rebellion in the United States, coronavirus infection can cause asymptomatic debate',
        color: '#FCFEC1',
        city: 'Hong Kong',
        coordinates: [22.3193, -114.1694],
        value: 100,
        tags: '',
        code: 'HK',
        date: '11 Mar 2020',
        outlet: 'TechNews',
        paragraph: 'The number of confirmed cases of pneumonia in Wuhan in the United States has increased sharply. Experts worry that there are many hidden cases, and the diagnosed patients may have no symptoms.',
    },
    
    
    
    
    
    // VPN: AUSTRALIA
    {
        id: '1',
        headline: 'Donald Trump declares coronavirus a US national emergency, frees up $75 billion in funds',
        color: '#FCFEC1',
        city: 'Melbourne',
        coordinates: [37.8136, -114.9631],
        value: 100,
        tags: '',
        code: 'AU',
        date: '14 Mar 2020',
        outlet: 'ABC Science Online',
        paragraph: 'US President Donald Trump has declared a national emergency over the fast-spreading coronavirus.',
    },
    {
        id: '2',
        headline: 'Donald Trump has banned all travel from 26 European countries to the United States. Here´s what we know',
        color: '#FCFEC1',
        city: 'Melbourne',
        coordinates: [37.8136, -114.9631],
        value: 100,
        tags: '',
        code: 'AU',
        date: '13 Mar 2020',
        outlet: 'ABC News',
        paragraph: 'It is pretty rare for US presidents to make addresses like these and goes to show how seriously the country is taking the coronavirus situation.',
    },
    {
        id: '3',
        headline: 'Tom Hanks Got Sick in Australia, Where Coronavirus Testing Isn’t Such a Hassle',
        color: '#FCFEC1',
        city: 'Melbourne',
        coordinates: [37.8136, -114.9631],
        value: 100,
        tags: '',
        code: 'AU',
        date: '12 Mar 2020',
        outlet: 'The New York Times',
        paragraph: 'In the United States, little if anything about the testing has been efficient or convenient.',
    },
    {
        id: '4',
        headline: 'Vital Signs: Australian and US rate cuts underline seriousness of the coronavirus crisis',
        color: '#FCFEC1',
        city: 'Melbourne',
        coordinates: [37.8136, -114.9631],
        value: 100,
        tags: '',
        code: 'AU',
        date: '6 Mar 2020',
        outlet: 'The Conversation AU',
        paragraph: 'This week the Reserve Bank of Australia did something everyone expected and the US Federal Reserve did something almost nobody expected.',
    },
    {
        id: '5',
        headline: 'Coronavirus: US death toll climbs to six, outbreak spreads to 11 states',
        color: '#FCFEC1',
        city: 'Melbourne',
        coordinates: [37.8136, -114.9631],
        value: 100,
        tags: '',
        code: 'AU',
        date: '3 Mar 2020',
        outlet: 'ABC Local',
        paragraph: 'The death toll from the coronavirus in the US has climbed to six, according to health officials.',
    },
    
    
    
    
    
    // VPN: MEXICO
    {
        id: '1',
        headline: 'Why is New York the epicenter of the coronavirus outbreak in the United States?',
        color: '#FCFEC1',
        city: 'Mexico City',
        coordinates: [19.4326, -99.1332],
        value: 100,
        tags: '',
        code: 'MX',
        date: '27 Mar 2020',
        outlet: 'CNN México',
        paragraph: 'There were more than 74,000 cases of coronavirus in the United States as of Thursday noon. About half in New York, almost 10 times more than in any other state.',
    },
    {
        id: '2',
        headline: 'President Trump decrees national emergency in the United States due to the coronavirus pandemic',
        color: '#FCFEC1',
        city: 'Mexico City',
        coordinates: [19.4326, -99.1332],
        value: 100,
        tags: '',
        code: 'MX',
        date: '13 Mar 2020',
        outlet: 'Telemundo',
        paragraph: 'At a press conference at the White House, Trump declared the emergency, which means the delivery of some 50,000 million dollars to face the pandemic across the country.',
    },
    {
        id: '3',
        headline: 'United States issues new guidelines to curb coronavirus',
        color: '#FCFEC1',
        city: 'Mexico City',
        coordinates: [19.4326, -99.1332],
        value: 100,
        tags: '',
        code: 'MX',
        date: '16 Mar 2020',
        outlet: 'San Diego Union-Tribune en Español',
        paragraph: 'Accelerating the pace to stop the expected increase in cases of the new coronavirus, the White House on Monday presented a series of guidelines that for the next 15 days will temporarily modify the norms of American society.',
    },
    {
        id: '4',
        headline: 'How many cases of coronavirus are there in the USA as of March 20?',
        color: '#FCFEC1',
        city: 'Mexico City',
        coordinates: [19.4326, -99.1332],
        value: 100,
        tags: '',
        code: 'MX',
        date: '20 Mar 2020',
        outlet: 'AS',
        paragraph: 'The increase in people sick with coronavirus continues to increase in the United States, and there are more than 16,000 cases as of March 20.',
    },
    {
        id: '5',
        headline: 'The United States outperforms China in coronavirus infections; is the new epicenter of the pandemic',
        color: '#FCFEC1',
        city: 'Mexico City',
        coordinates: [19.4326, -99.1332],
        value: 100,
        tags: '',
        code: 'MX',
        date: '26 Mar 2020',
        outlet: 'El Diario NY',
        paragraph: 'As announced by the World Health Organization (WHO) earlier this week, the United States became the new epicenter of the coronavirus pandemic.',
    },

    ]
  },
  br: {
    markers: [
      {
        id: 'USCA1',
        headline: 'U.S. announces new travel restrictions amid novel coronavirus pandemic',
        color: 'red',
        city: 'Toronto',
        coordinates: [43.6532, -79.3832],
        value: 100,
        tags: '',
        code: 'CA',
        date: '14 Mar 2020',
        outlet: 'Global News',
        paragraph: 'Donald Trump and Mike Pence announced Saturday that the United States will broaden its European travel ban, adding the United Kingdom and Ireland to its list, and was considering imposing restrictions on travel within the U.S. to areas hit hard by the coronavirus spread.',
      },
    ]
  },
  ch: {
    markers: [
      {
        id: 'USCA1',
        headline: 'U.S. announces new travel restrictions amid novel coronavirus pandemic',
        color: 'red',
        city: 'Toronto',
        coordinates: [43.6532, -79.3832],
        value: 100,
        tags: '',
        code: 'CA',
        date: '14 Mar 2020',
        outlet: 'Global News',
        paragraph: 'Donald Trump and Mike Pence announced Saturday that the United States will broaden its European travel ban, adding the United Kingdom and Ireland to its list, and was considering imposing restrictions on travel within the U.S. to areas hit hard by the coronavirus spread.',
      },
    ]
  },
  fi: {
    markers: [
      //VPN: US
      //VPN: CANADA
      
      //VPN: Belgium
      {
        id: '11',
        headline: 'Finland, the happiest country in the world, may handle coronavirus better than the US',
        color: '#FCFEC1',
        city: 'Brussels',
        coordinates: [50.8503, 4.3517],
        value: 100,
        tags: '',
        code: 'BE',
        date: '21 Mar 2020',
        outlet: 'Business Insider UK',
        paragraph: 'For the third year in a row, the UN has named Finland the happiest country in the world. This year, the UN said that one of the main reasons Finland ranked as the happiest country could help it deal with the challenges of the coronavirus pandemic better than other nations.',
      },
      {
        id: '12',
        headline: 'Finland Cuts Off Helsinki Region In Coronavirus Clampdown',
        color: '#FCFEC1',
        city: 'Brussels',
        coordinates: [50.8503, 4.3517],
        value: 100,
        tags: '',
        code: 'BE',
        date: '25 Mar 2020',
        outlet: 'Forbes',
        paragraph: 'Finland has already closed its borders to non-residents, closed schools and limited public gatherings to a maximum of 10 people in a bid to slow the spread of the novel coronavirus COVID-19.',
      },
      {
        id: '13',
        headline: 'Finland former president has coronavirus',
        color: '#FCFEC1',
        city: 'Brussels',
        coordinates: [50.8503, 4.3517],
        value: 100,
        tags: '',
        code: 'BE',
        date: '24 Mar 2020',
        outlet: 'EUobserver',
        paragraph: 'Finland´s former president, Martti Ahtisaari, has been diagnosed with coronavirus, according to a statement from the office of the president.',
      },
      {
        id: '14',
        headline: 'Finland Invokes Emergency Powers to Slow Coronavirus Spread',
        color: '#FCFEC1',
        city: 'Brussels',
        coordinates: [50.8503, 4.3517],
        value: 100,
        tags: '',
        code: 'BE',
        date: '16 Mar 2020',
        outlet: 'Bloomberg',
        paragraph: 'Finland government is preparing to invoke emergency powers to combat the spread of the novel coronavirus.',
      },
      {
        id: '15',
        headline: 'Finland install further measures to prevent the spread of the coronavirus',
        color: '#FCFEC1',
        city: 'Brussels',
        coordinates: [50.8503, 4.3517],
        value: 100,
        tags: '',
        code: 'BE',
        date: '27 Mar 2020',
        outlet: 'ScandAsia.com',
        paragraph: 'Nationwide, Finland has confirmed 880 cases of COVID-19 and three deaths: the spread of the virus is further along in the region of Uusimaa.',
      },
      //VPN Denmark
      {
        id: '16',
        headline: 'Finland, the happiest country in the world, may handle coronavirus better than the US',
        color: '#FCFEC1',
        city: 'Copenhagen',
        coordinates: [55.6761, 12.5683],
        value: 100,
        tags: '',
        code: 'DK',
        date: '21 Mar 2020',
        outlet: 'Business Insider UK',
        paragraph: 'For the third year in a row, the UN has named Finland the happiest country in the world. This year, the UN said that one of the main reasons Finland ranked as the happiest country could help it deal with the challenges of the coronavirus pandemic better than other nations.',
      },
      {
        id: '17',
        headline: 'Finland Invokes Emergency Powers to Slow Coronavirus Spread',
        color: '#FCFEC1',
        city: 'Copenhagen',
        coordinates: [55.6761, 12.5683],
        value: 100,
        tags: '',
        code: 'DK',
        date: '16 Mar 2020',
        outlet: 'Bloomberg',
        paragraph: 'Finland government is preparing to invoke emergency powers to combat the spread of the novel coronavirus.',
      },
      {
        id: '18',
        headline: 'Finland Cuts Off Helsinki Region In Coronavirus Clampdown',
        color: '#FCFEC1',
        city: 'Copenhagen',
        coordinates: [55.6761, 12.5683],
        value: 100,
        tags: '',
        code: 'DK',
        date: '25 Mar 2020',
        outlet: 'Forbes',
        paragraph: 'Finland has already closed its borders to non-residents, closed schools and limited public gatherings to a maximum of 10 people in a bid to slow the spread of the novel coronavirus COVID-19.',
      },
      {
        id: '19',
        headline: 'Finland former president has coronavirus',
        color: '#FCFEC1',
        city: 'Copenhagen',
        coordinates: [55.6761, 12.5683],
        value: 100,
        tags: '',
        code: 'DK',
        date: '24 Mar 2020',
        outlet: 'EUobserver',
        paragraph: 'Finland former president, Martti Ahtisaari, has been diagnosed with coronavirus, according to a statement from the office of the president.',
      },
      {
        id: '20',
        headline: 'Finland install further measures to prevent the spread of the coronavirus',
        color: '#FCFEC1',
        city: 'Copenhagen',
        coordinates: [55.6761, 12.5683],
        value: 100,
        tags: '',
        code: 'DK',
        date: '27 Mar 2020',
        outlet: 'ScandAsia.com',
        paragraph: 'Nationwide, Finland has confirmed 880 cases of COVID-19 and three deaths: the spread of the virus is further along in the region of Uusimaa.',
      },
      //VPN Suomi
      {
        id: '21',
        headline: 'At what stage is the coronavirus epidemic in Finland?',
        color: '#FCFEC1',
        city: 'Helsinki',
        coordinates: [60.1699, 24.9384],
        value: 100,
        tags: '',
        code: 'FI',
        date: '20 Mar 2020',
        outlet: 'YLE',
        paragraph: 'This article gives you a quick overview of the basics of the coronavirus epidemic in Finland.',
      },
      {
        id: '21',
        headline: 'Yle´s data: Estimates of the spread of the coronavirus in Finland have intensified - intensive care capacity becomes tight',
        color: '#FCFEC1',
        city: 'Helsinki',
        coordinates: [60.1699, 24.9384],
        value: 100,
        tags: '',
        code: 'FI',
        date: '25 Mar 2020',
        outlet: 'YLE',
        paragraph: 'The government counts Uusimaa infections from the municipality to find out which area is being isolated.',
      },
      {
        id: '23',
        headline: 'This is how the coronavirus has spread in Finland: See here for infections and the latest information',
        color: '#FCFEC1',
        city: 'Helsinki',
        coordinates: [60.1699, 24.9384],
        value: 100,
        tags: '',
        code: 'FI',
        date: '9 Mar 2020',
        outlet: 'MTV Uutiset',
        paragraph: 'The number of people suffering from coronavirus in Finland is increasing day by day.',
      },
      {
        id: '24',
        headline: 'Coronavirus: Two new deaths in Finland',
        color: '#FCFEC1',
        city: 'Helsinki',
        coordinates: [60.1699, 24.9384],
        value: 100,
        tags: '',
        code: 'FI',
        date: '25 Mar 2020',
        outlet: 'Kauppalehti',
        paragraph: 'According to the Kanta-Häme Hospital District, one person has died of a coronavirus disease in Kanta-Häme.',
      },
      {
        id: '25',
        headline: 'Coronavirus: 33 cases in Finland now - 3 infections in Central Finland',
        color: '#FCFEC1',
        city: 'Helsinki',
        coordinates: [60.1699, 24.9384],
        value: 100,
        tags: '',
        code: 'FI',
        date: '9 Mar 2020',
        outlet: 'Uusi Suomi',
        paragraph: 'A total of 33 cases of corona have now been reported in Finland.',
      },
    ]
  },
  eg: {
    markers: [
      {
        id: 'USCA1',
        headline: 'U.S. announces new travel restrictions amid novel coronavirus pandemic',
        color: 'red',
        city: 'Toronto',
        coordinates: [45.6532, -69.3832],
        value: 100,
        tags: '',
        code: 'CA',
        date: '14 Mar 2020',
        outlet: 'Global News',
        paragraph: 'Donald Trump and Mike Pence announced Saturday that the United States will broaden its European travel ban, adding the United Kingdom and Ireland to its list, and was considering imposing restrictions on travel within the U.S. to areas hit hard by the coronavirus spread.',
      },
    ]
  },
  au: {
    markers: [
      {
        id: 'USCA1',
        headline: 'U.S. announces new travel restrictions amid novel coronavirus pandemic',
        color: 'red',
        city: 'Toronto',
        coordinates: [48.6532, -89.3832],
        value: 100,
        tags: '',
        code: 'CA',
        date: '14 Mar 2020',
        outlet: 'Global News',
        paragraph: 'Donald Trump and Mike Pence announced Saturday that the United States will broaden its European travel ban, adding the United Kingdom and Ireland to its list, and was considering imposing restrictions on travel within the U.S. to areas hit hard by the coronavirus spread.',
      },
    ]
  },
}


export {
  AllMarkersByCountry
}
