
const AllMarkersByCountry = {
  us: {
    markers: [
      {
        id: 'USCA1',
        headline: 'U.S. announces new travel restrictions amid novel coronavirus pandemic',
        color: 'red',
        city: 'Toronto',
        coordinates: [43.6532, -79.3832],
        value: 100,
        tags: '',
        code: 'CA',
        date: '14 Mar 2020',
        outlet: 'Global News',
        paragraph: 'Donald Trump and Mike Pence announced Saturday that the United States will broaden its European travel ban, adding the United Kingdom and Ireland to its list, and was considering imposing restrictions on travel within the U.S. to areas hit hard by the coronavirus spread.',
    },
    {
        id: 'USCA2',
        headline: 'Trump to provide update on U.S. coronavirus measures, including executive actions',
        color: 'red',
        city: 'Toronto',
        coordinates: [43.6532, -79.3832],
        value: 100,
        tags: '',
        code: 'CA',
        date: '11 Mar 2020',
        outlet: 'Global News',
        paragraph: 'U.S. President Donald Trump was considering a national disaster declaration and new travel advisories while Congress unveiled a coronavirus aid package as Washington raced Wednesday to confront the outbreak that’s moving dramatically across the country and disrupting the daily lives of Americans.',
    },
    {
        id: 'USCA3',
        headline: 'Coronavirus: California declares emergency after death',
        color:  'red',
        city: 'Toronto',
        coordinates: [43.6532, -79.3832],
        value: 100,
        tags: '',
        code: 'CA',
        date: '5 Mar 2020',
        outlet: 'BBC',
        paragraph: 'California has declared a state of emergency after announcing its first coronavirus death, bringing the US death toll from the disease to 11.',
    },
    {
        id: 'USCA4',
        headline: '6 people have died from novel coronavirus in the US as cases nationwide surge',
        color: 'red',
        city: 'Toronto',
        coordinates: [43.6532, -79.3832],
        value: 100,
        tags: '',
        code: 'CA',
        date: '3 Mar 2020',
        outlet: 'CNN',
        paragraph: 'Six people have died in Washington state as the United States grapples with more than 100 cases of the disease caused by the novel coronavirus.',
    },
    {
        id: 'USCA5',
        headline: 'U.S. House passes sweeping coronavirus aid package, including free testing',
        color: 'green',
        city: 'Toronto',
        coordinates: [43.6532, -79.3832],
        value: 100,
        tags: '',
        code: 'CA',
        date: '14 Mar 2020',
        outlet: 'Global News',
        paragraph: 'The U.S. House of Representatives has passed a sweeping coronavirus aid package that includes free testing and paid sick leave for workers, just hours after U.S. President Donald Trump declared a national emergency due to the pandemic.',
    },
  ]},
  it: {
    markers: [
      {
        id: 2,
        headline1: 'Beef Consumption has increased by 35%',
        headline2: 'Space Investigation In Trouble due to Infections',
        headline3: 'Hollywood is in Financial Difficulties',
        headline4: 'Silicon Valley`s tips for Remote Working',
        headline5: 'California is Still considered safe zone',
        color: 'red',
        city: 'Istanbul',
        coordinates: [31.5074, -100],
        value: 80,
      },
      {
        id: 3,
        headline1: 'Universities Supporting Healthcare Professionals ',
        headline2: 'Tourism dropped by -120% in San Francisco',
        headline3: 'Hollywood is in Financial Difficulties',
        headline4: 'Silicon Valley`s tips for Remote Working',
        headline5: 'California is Still considered safe zone',
        color: 'red',
        city: 'Barcelona',
        coordinates: [36, -119],
        value: 80,
      },
      {
        id: 4,
        headline1: 'Universities Supporting Healthcare Professionals ',
        headline2: 'Tourism dropped by -120% in San Francisco',
        headline3: 'Hollywood is in Financial Difficulties',
        headline4: 'Silicon Valley`s tips for Remote Working',
        headline5: 'California is Still considered safe zone',
        color: 'red',
        city: 'London',
        coordinates: [28, -119],
        value: 80,
      },
           {
        id: 5,
        headline1: 'Universities Supporting Healthcare Professionals ',
        headline2: 'Tourism dropped by -120% in San Francisco',
        headline3: 'Hollywood is in Financial Difficulties',
        headline4: 'Silicon Valley`s tips for Remote Working',
        headline5: 'California is Still considered safe zone',
        color: 'red',
        city: 'Stockholm',
        coordinates: [15, -95],
        value: 80,
      },
    ]
  },
   ch: {
    markers: [
      {
        id: 2,
        headline1: 'Economy news!',
        headline2: 'Economy news 2!',
        headline3: 'Economy news!',
        headline4: 'Still',
        headline5: 'Economy news still!',
        color: 'red',
        city: 'Helsinki',
        coordinates: [14, -10],
        value: 80,
      },
      {
        id: 3,
        headline1: 'Economy news!',
        headline2: 'Economy news 2!',
        headline3: 'Economy news!',
        headline4: 'Still',
        headline5: 'Economy news still!',
        color: 'red',
        city: 'London',
        coordinates: [26, -129],
        value: 80,
      },
      {
        id: 4,
        headline1: 'Economy news!',
        headline2: 'Economy news 2!',
        headline3: 'Economy news!',
        headline4: 'Still',
        headline5: 'Economy news still!',
        color: 'yellow',
        city: 'Paris',
        coordinates: [24, -149],
        value: 80,
      },
           {
        id: 5,
        headline1: 'Economy news!',
        headline2: 'Economy news 2!',
        headline3: 'Economy news!',
        headline4: 'Still',
        headline5: 'Economy news still!',
        color: 'red',
        city: 'NYC',
        coordinates: [35, -115],
        value: 80,
      },
    ]
  }
}


export {
  AllMarkersByCountry
}
